#Example configuration options that can be placed in your main SiriProxy config.yml


###########################
NOTICE: Modifying these options in this file has no effect. You must put them in SiriProxy's config.yml! 
###########################


            - name: 'SWSB'
            git: 'git://github.com/SparkysWidgets/SiriProxy-SWSB.git'
            comport: '/dev/rfcomm1'
            baudrate: 9600
            databits: 8
            stopbits: 1
            parity: 0